language: objective-c

notifications:
  email:
    on_success: never
    on_failure: change

env:
  - APM_TEST_PACKAGES="pigments"

script: 'curl -s https://raw.githubusercontent.com/abe33/minimap-pigments/master/ci/build-package.sh | sh'
